### ISSUE TITLE
Server Settings Locked/Greyed Out

### ISSUE THREAD

**Issue by shinyben** [G4me4u/g4mespeed#15]
After using the `G` hotkey, I'm not able to edit the server settings. `settings.cfg` is also hex, so I can't modify the setting directly. I'm trying to allow hotkeys in survival.

**Comment by G4me4u** [comment]
That is a feature, not a bug - you need to enable cheats (i.e be OP) for that. However, since the settings are global across all single player worlds, you can solve it by making a new world with cheats enabled (during creation), change the setting there, and delete the temporary world. Then the setting persists in the other world.
