### ISSUE TITLE
[BUG] Item stuttering

### ISSUE THREAD

**Issue by Wikinger8** [G4me4u/g4mespeed#7]
https://github.com/G4me4u/g4mespeed/assets/85295145/01e8a1e5-0af3-4807-a896-33aece4d3d05

When I use a shader and have "Fixed movement speed" activated, my items start to stutter in my hands.

**Comment by G4me4u** [comment]
Hey! Thanks for reaching out.

Is this using default 20 tps? Because fixed movement should automatically deactivate if that is the case. It is also possible that you have the Block Event Separator mod installed, which always activates fixed movement (even at default tps).

It's a bit tricky to fix this issue, since the shader uses the global delta time. But I can take a look at it.

**Comment by Wikinger8** [comment]
Yeah I also had Block Event Separator installed and I used the default 20 tps. I think I used the Sildur's Vibrant shader with the Iris fabric mod.

**Comment by G4me4u** [comment]
Unfortunately, unless solved by the shader owner/Iris, this is not possible to solve here.

They are using the incorrect time delta, as I mentioned, which is what I (must) modify.
They do not comply with vanilla behavior in this case.
